### ISSUE TITLE
The game crashes once I installed SAUtils

### ISSUE THREAD

**Issue by ifn00** [AndroidModLoader/SAUtils#1]
i don't know if this ever happened to anyone but this problem makes the game unplayable AT ALL, once i installed SAUtils and run the game, it won't let me, it's force close instead and im clueless about this, i thought this is a common problem but no, no one has ever made a video or blog or anything about this crash, it's not crash once i click on my save game, but quickly force close like it's not made for my phone...

https://github.com/AndroidModLoader/SAUtils/assets/155373074/ea71d983-a4f0-4457-a3ca-f3c1b3d167d8

**Comment by RusJJ** [comment]
Use the latest official APK, not a random poop from the internet

**Comment by ifn00** [comment]
alright, so, can you provide me a link to the official latest apk?, or is
there a specific website to download the latest version of the game?, if
there is, please give me the link and thanks for the help (i'm going insane)

**Comment by MRCTOTHEJCJ** [comment]
I have this issue

**Comment by MRCTOTHEJCJ** [comment]
> Use the latest official APK, not a random poop from the internet

Link?!
